// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1o7ecyuJB9pmMLYkcjnjEYjhyyHHaLfI',
    appId: '1:202012320145:web:0738cb21df85e83b743a30',
    messagingSenderId: '202012320145',
    projectId: 'instagram-clone-914f6',
    authDomain: 'instagram-clone-914f6.firebaseapp.com',
    storageBucket: 'instagram-clone-914f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpayM5EppLJofqtSV2xCDtA9NHuxC9BjY',
    appId: '1:202012320145:android:75531e3a25b1f7b9743a30',
    messagingSenderId: '202012320145',
    projectId: 'instagram-clone-914f6',
    storageBucket: 'instagram-clone-914f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPnvRyS8hlzp_i3zkZVikIcyjzxawpCnQ',
    appId: '1:202012320145:ios:c40b907e427a4752743a30',
    messagingSenderId: '202012320145',
    projectId: 'instagram-clone-914f6',
    storageBucket: 'instagram-clone-914f6.appspot.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
